# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a14b3b94959354666e118870f9207afc0d56cfe75ca42282e8632f92446fd7549b9022896eeb466e855c02d4f31f0cda5cc70f3581a3896ae42bae2c21026edb

test:
  secret_key_base: fcfc258065433fe6a58120e98fa4e7ed48edd222a1a08d0f28f7b99127df5794cc862c1a2de9264bab50004551efd5bd1fbcc4e337097df558e74658055cdc3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
